### ISSUE TITLE
Implement trip logger

### ISSUE THREAD

**Issue by Mineshafter61** [Limaru-Minecraft/iciwi#27]
maybe implement it as a thing within Iciwi's SQL?

**Comment by Mineshafter61** [comment]
Ok im changing things up a bit and implementing this as a CSV

Which format do you prefer: 
* <id>, <action: enter/exit>, <username>, <card/ticket type>, <card/ticket number>, <starting station>, <price>, <fare class>, <transfer reference ID>
* <id>, <action: enter/exit>, <username>, <card/ticket type>, <card/ticket number>, <starting station>, <price>, <fare class>, [TRF <same thing again for transfers>]

The first will be easier to code but harder to read, the second will be harder to code but can get very long.

Also should fare gates log _every_ entry and exit, or only on exit?

**Comment by Mineshafter61** [comment]
Enhancement: the trip logger should update its stats onto a webpage as well

**Comment by Mineshafter61** [comment]
Instead of fumbling around with formats, I think it'll be better if I listed every single type of transaction here and see how to sort them.

# Ticket machines
## New ticket
- Timestamp
- Username
- Card Serial
- Card New (Current) Value

## Top Up
- Timestamp
- Username
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card New (Current) Value
- Card Old Value


## Refund
- Timestamp
- Username
- Card
- - Serial
- - Railpasses
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value

## New Railpass
- Timestamp
- Username
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value
- New Railpass
- - Name
- - Cost
- - Discount Percentage
- - Start Time
- - Duration
- - Company

## New Ticket
- Timestamp
- Username
- Ticket Cost
- Company Payment Table
- - Company Paid
- - Value of payment
- Start Station
- End Station
- Fare class

# Faregates
## Entry (normal, card)
- Timestamp
- Username
- Sign coords
- Station
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value

## Exit (normal, card)
- Timestamp
- Username
- Sign coords
- Station
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value
- Journey
- - Entry
- - - Timestamp
- - - Station
- - Exit
- - - Timestamp
- - - Station
- - Fare class
- - Transaction
- - - Original Fare
- - - Railpasses Used
- - - - Name
- - - - Cost
- - - - Discount Percentage
- - - - Start Time
- - - - Duration
- - - - Company
- - - Final Fare

## Entry (transfer, card)
- Timestamp
- Username
- Sign coords
- Station
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value
- Previous Journey
- - Entry
- - - Timestamp
- - - Station
- - Exit
- - - Timestamp
- - - Station
- - Fare class
- - Transaction
- - - Original Fare
- - - Railpasses Used
- - - - Name
- - - - Cost
- - - - Discount Percentage
- - - - Start Time
- - - - Duration
- - - - Company
- - - Final Fare


## Exit (transfer, card)
- Timestamp
- Username
- Sign coords
- Station
- Card
- - Serial
- - Railpass List
- - - Name
- - - Cost
- - - Discount Percentage
- - - Start Time
- - - Duration
- - - Company
- - Card Current Value
- Journey
- - Entry
- - - Timestamp
- - - Station
- - Exit
- - - Timestamp
- - - Station
- - Fare class
- - Transaction
- - - Original Fare for this leg
- - - Amended Fare
- - - - Start Station
- - - - End Station
- - - - Class
- - - - Fare Value
- - - Railpasses Used
- - - - Name
- - - - Cost
- - - - Discount Percentage
- - - - Start Time
- - - - Duration
- - - - Company
- - - Final Fare
- Previous Journey
- - Entry
- - - Timestamp
- - - Station
- - Exit
- - - Timestamp
- - - Station
- - Fare class
- - Transaction
- - - Original Fare
- - - Railpasses Used
- - - - Name
- - - - Cost
- - - - Discount Percentage
- - - - Start Time
- - - - Duration
- - - - Company
- - - Final Fare

## Entry (ticket)
- Timestamp
- Username
- Sign coords
- Station
- Ticket
- - Start
- - End
- - Class

## Exit (ticket)
- Timestamp
- Username
- Sign coords
- Station
- Ticket
- - Start
- - End
- - Class
- Journey
- - Entry
- - - Timestamp
- - - Station
- - Exit
- - - Timestamp
- - - Station
- - Fare class
- - Transaction
- - - Original Fare
- - - Railpasses Used (none)
- - - - Name
- - - - Cost
- - - - Discount Percentage
- - - - Start Time
- - - - Duration
- - - - Company
- - - Final Fare

**Comment by Mineshafter61** [comment]
I think one feature we can consider is adding serial numbers to tickets

**Comment by Mineshafter61** [comment]
@muffinbarde that would greatly help, thanks!

BTW i also only have a laptop but Vim is my go-to IDE, therefore I'm not affected by performance just as much when coding. If you're open to IDE suggestions, I suggest trying out [Helix](https://helix-editor.com).

**Comment by muffinbarde** [comment]
@Mineshafter61 Thx for the suggestions; for me it's rather that I can't not try out what I coded without a mouse because playing the game without it is soo difficult and unpleasent. So I still have to wait for my mouse to arrive. Just write me on Discord once you need my help.

**Comment by Mineshafter61** [comment]
Milestones:
- [*] table creation
- [*] fare gate logging
- [ ] ticket machine logging
