### ISSUE TITLE
Terrible code

### ISSUE THREAD

**Issue by Mineshafter61** [Limaru-Minecraft/iciwi#42]
https://github.com/Limaru-Minecraft/iciwi/blob/master/src/main/java/mikeshafter/iciwi/tickets/CustomMachine.java#L168-L209

I cringe when I see this method. This is absolutely horrendous and sinful, not to mention that it breaks every law, convention, guideline, physical theory and mathematical theorem. My therapist needs therapy when she sees this. To give you a scale of how bad this code is, when Satan sees this, hell literally falls into a black hole and ceases to exist. This code is equivalent to destroying humanity 69420 times over. Erase and redo this method, or else the universe is doomed.

**Comment by nwnisworking** [comment]
This code has given me a gargantuan migraine. 10/10 <3
